# Generated by Django 3.1.4 on 2020-12-28 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название вопроса')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
                ('who_can_view', models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE'), ('MO', 'MODERATION')], default='PR', max_length=2)),
                ('who_can_view_comments', models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE')], default='PR', max_length=2)),
                ('topic', models.CharField(choices=[('H', 'HOBBY'), ('L', 'LOVE'), ('N', 'NATURE'), ('F', 'FUTURE'), ('O', 'OTHER')], default='O', max_length=1, verbose_name='тема вопроса')),
                ('authors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('text', models.TextField(verbose_name='текст ответа')),
                ('who_can_view', models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE'), ('MO', 'MODERATION')], default='PR', max_length=2)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.article')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
