# Generated by Django 3.1.4 on 2021-01-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(choices=[('H', 'HOBBY'), ('L', 'LOVE'), ('N', 'NATURE'), ('F', 'FUTURE'), ('O', 'OTHER')], default='O', max_length=1, verbose_name='тема статьи'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('who_can_view_answer', models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE')], default='PR', max_length=2)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.article')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('text', models.TextField(verbose_name='текст ответа')),
                ('who_can_view', models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE'), ('MO', 'MODERATION')], default='PR', max_length=2)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
