# Generated by Django 3.1.4 on 2021-01-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20210102_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='who_can_view_answer',
            new_name='who_can_view_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Q', 'QUESTION'), ('C', 'CHECKBOX'), ('R', 'RADIO')], default='Q', max_length=1),
        ),
    ]
