# Generated by Django 3.1.4 on 2021-01-03 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20210102_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст варианта')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.question')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Вырианты',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст варианта')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.answer')),
            ],
            options={
                'verbose_name': 'Вариант, который выбрали',
                'verbose_name_plural': 'Вырианты, которые выбрали',
            },
        ),
    ]
