# Generated by Django 3.1.4 on 2021-01-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_answeroption_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'verbose_name': 'Вариант, который выбрали', 'verbose_name_plural': 'Варианты, которые выбрали'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
    ]
