# Generated by Django 3.1.4 on 2021-01-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_auto_20210103_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='who_can_view',
        ),
    ]
