# Generated by Django 3.1.4 on 2021-01-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_remove_answer_who_can_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='who_can_view_answers',
        ),
    ]
