# Generated by Django 3.1.4 on 2021-01-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_remove_question_who_can_view_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='who_can_view',
            new_name='access',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='who_can_view_comments',
            new_name='comment_access',
        ),
    ]
