# Generated by Django 3.1.4 on 2021-01-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_auto_20210104_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='who_can_view',
            new_name='access',
        ),
    ]
