# Generated by Django 3.1.4 on 2021-01-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_auto_20210104_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-id'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='answeroption',
            options={'ordering': ['-id'], 'verbose_name': 'Вариант, который выбрали', 'verbose_name_plural': 'Варианты, которые выбрали'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['-id'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='answer',
            name='author_pk',
            field=models.IntegerField(default=0, verbose_name='идентификатор автора'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_pk',
            field=models.IntegerField(default=0, verbose_name='идентификатор автора'),
        ),
    ]
