# Generated by Django 3.1.4 on 2021-01-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_auto_20210106_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_pk',
        ),
    ]
