# Generated by Django 3.1.4 on 2021-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0011_remove_comment_author_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=70, null=True, unique=True),
        ),
    ]
