# Generated by Django 3.1.4 on 2021-01-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0012_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='access',
            field=models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE'), ('MO', 'MODERATION')], default='PR', max_length=2, verbose_name='доступ к статье'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_access',
            field=models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE')], default='PR', max_length=2, verbose_name='настройки комментариев'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=70, null=True, unique=True, verbose_name='слаг'),
        ),
    ]
