# Generated by Django 3.1.4 on 2021-01-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0013_auto_20210117_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='access',
            field=models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE'), ('MO', 'MODERATION')], default='PR', max_length=2, verbose_name='доступ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(choices=[('H', 'HOBBY'), ('L', 'LOVE'), ('N', 'NATURE'), ('F', 'FUTURE'), ('O', 'OTHER')], default='O', max_length=1, verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='access',
            field=models.CharField(choices=[('PU', 'PUBLIC'), ('PR', 'PRIVATE'), ('MO', 'MODERATION')], default='PR', max_length=2, verbose_name='доступ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Q', 'QUESTION'), ('C', 'CHECKBOX'), ('R', 'RADIO')], default='Q', max_length=1, verbose_name='тип'),
        ),
    ]
