# Generated by Django 3.1.4 on 2021-03-14 19:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logic', '0014_auto_20210117_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadawanProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=16, verbose_name='телефон')),
                ('notes', models.TextField(verbose_name='заметки')),
                ('rank', models.CharField(choices=[('01', 'Рядовой соботыльник'), ('02', 'Младший сержант бота'), ('03', 'Сержант олимпиад'), ('04', 'Старшина перечней'), ('05', 'Товарищ прапорщик'), ('06', 'Старший соботыльник'), ('07', 'Лейтенант учёбы'), ('08', 'Капитан региона'), ('09', 'Майор тайм-менеджмента'), ('10', 'Полковник-бвишник'), ('11', 'Генерал всерос(с)а'), ('12', 'Магистр книг и пособий'), ('13', 'Повелитель бота'), ('14', 'Император всея Бота и Учёбы')], default='01', max_length=2, verbose_name='звание')),
                ('off_date', models.DateField(verbose_name='окончание оплаченного периода')),
                ('weekend', models.CharField(choices=[('1', 'понедельник'), ('2', 'вторник'), ('3', 'среда'), ('4', 'четверг'), ('5', 'пятница'), ('6', 'суббота'), ('7', 'воскресенье')], default='7', max_length=1, verbose_name='выходной')),
                ('group', models.CharField(choices=[('P', 'Pro'), ('L', 'Lite')], default='L', max_length=1, verbose_name='группа')),
                ('utc', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(12)], verbose_name='временной сдвиг')),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подаван',
                'verbose_name_plural': 'Подваны',
                'ordering': ['-off_date'],
            },
        ),
        migrations.RemoveField(
            model_name='answeroption',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='article',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
