# Generated by Django 3.1.4 on 2021-03-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0016_auto_20210314_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padawanprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='заметки'),
        ),
        migrations.AlterField(
            model_name='padawanprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, verbose_name='телефон'),
        ),
    ]
