# Generated by Django 3.1.4 on 2021-03-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0017_auto_20210314_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padawanprofile',
            name='off_date',
            field=models.DateField(auto_now=True, verbose_name='окончание оплаченного периода'),
        ),
    ]
