# Generated by Django 3.1.4 on 2021-03-15 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logic', '0018_auto_20210314_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padawanprofile',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padawans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='padawanprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padawanProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CuratorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='сuratorProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
            },
        ),
    ]
