# Generated by Django 3.1.4 on 2021-03-15 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0019_auto_20210315_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='padawanprofile',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='рейтинг'),
        ),
    ]
