# Generated by Django 3.1.4 on 2021-03-30 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0020_padawanprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padawanprofile',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padawans', to='logic.curatorprofile'),
        ),
        migrations.AlterField(
            model_name='padawanprofile',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-20)], verbose_name='рейтинг'),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='время')),
                ('activations', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='активации')),
                ('text', models.SlugField(verbose_name='текст')),
                ('users', models.ManyToManyField(null=True, related_name='activateCodes', to='logic.PadawanProfile')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Коды',
                'ordering': ['-days'],
            },
        ),
    ]
