# Generated by Django 3.1.4 on 2021-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0022_auto_20210330_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='users',
            field=models.ManyToManyField(related_name='activatedCodes', to='logic.PadawanProfile'),
        ),
    ]
