# Generated by Django 3.1.4 on 2021-03-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0024_auto_20210330_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='activatedCodes', to='logic.PadawanProfile'),
        ),
    ]
