# Generated by Django 3.1.4 on 2020-12-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.CharField(max_length=200, verbose_name='вопрос')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
                ('complaint_answer', models.CharField(max_length=200, verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
