# Generated by Django 3.1.4 on 2020-12-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_auto_20201230_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='pub_date',
        ),
    ]
